### ISSUE TITLE
Improve syntax

### ISSUE THREAD

**Issue by johannes-z** [johannes-z/dnd-yml2svg#2]
## Current Syntax:

```YML
name : string

connectors : [connector]
connector :
  &alias
  name : string
  href : string

traps : [trap]
trap :
  &alias
  name : string
  type : mechanical | magic
  attack : string
  damage : string
  search : number
  disable : number
  spell:
    name : string
    damage : string
    href: string
  metamagic:
    name : string
    href : string
  href : string
  info : string
  show_spell : bool

encounters : [encounter]
encounter :
  &alias
  name : string
  monsters : [monster]

monster :
  &alias
  name : string
  amount : number
  href : string

locations : [location]
location :
  &alias
  id : string
  name : string
  encounters : encounters

connections : [connection]
connection :
  from : location
  to : location
  via : [via]
via :
  connector
  info : string
  hidden : number
  locked : number
  traps : traps

```
